<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>GoodMovies.ViewModels</RootNamespace>
    <AssemblyName>GoodMovies.ViewModels</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GoodMovies.Core\GoodMovies.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GoodMovies.Maui" />
    <InternalsVisibleTo Include="GoodMovies.ViewModels.Tests" />
  </ItemGroup>
</Project>
